### ISSUE TITLE
[Bug] platforms_to_flush not available from within a GPU callback

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4jax/mpi4jax#139]
Seen when running a particular functionality of netket that uses host callabacks on GPU.

I think that what is happening is that a host-callback called from GPU is calling back into mpi which is hitting this.

I'll eventually try to create a MWE of this

```
0 -> [GpuDevice(id=0, process_index=0)]
  0%|          | 0.00/4.00 [00:00<?, ?it/s, n=0]ERROR:absl:Outside call <jax.experimental.host_callback._CallbackWrapper object at 0x7f4cc43afaf0> threw exception '_thread._local' object has no attribute 'platforms_to_flush'.
2022-04-26 16:16:36.669549: E external/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/infeed_thunk.cc:48) ShapeUtil::Equal(dest_slices_[index].shape, source_shape) Mismatch between infeed source buffer shape s8[12345]{0} and infeed dest buffer shape f64[8,2]{1,0}
*** Begin stack trace ***

...

2022-04-26 16:16:36.669638: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2141] Execution of replica 0 failed: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/infeed_thunk.cc:48) ShapeUtil::Equal(dest_slices_[index].shape, source_shape) Mismatch between infeed source buffer shape s8[12345]{0} and infeed dest buffer shape f64[8,2]{1,0}
ERROR:absl:Postponing exception raised in callback function: Traceback (most recent call last):
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1823, in _callback_input_received
    return callback(arrays, device)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1167, in _outside_call_run_callback
    res = callback(arg, device, unpacked_transforms)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 721, in __call__
    return self.callback_func(arg)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/experimental/driver/tdvp.py", line 540, in <lambda>
    lambda args_and_kw: odefun(state, driver, *args_and_kw[0], **args_and_kw[1]),
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/experimental/driver/tdvp.py", line 504, in odefun
    driver._loss_stats, driver._loss_grad = state.expect_and_grad(
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/vqs/mc/mc_state/state.py", line 595, in expect_and_grad
    return expect_and_grad(
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/vqs/base.py", line 381, in expect_and_grad
    return expect_and_grad(
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/vqs/mc/mc_state/expect_grad_chunked.py", line 49, in expect_and_grad_nochunking
    return expect_and_grad(vstate, operator, use_covariance, *args, **kwargs)
  File "/home/filippovicentini/Dropbox/Ricerca/12-redo/ARDM/ARDM/vqs/expect_mc_grad.py", line 54, in expect_and_grad
    Ō, Ō_grad, new_model_state = grad_expect_hermitian(
  File "/home/filippovicentini/Dropbox/Ricerca/12-redo/ARDM/ARDM/vqs/expect_mc_grad.py", line 100, in grad_expect_hermitian
    correction = correction / stats.mean(correction)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/stats/mpi_stats.py", line 62, in mean
    out, _ = mpi.mpi_mean_jax(out)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/utils/mpi/primitives.py", line 129, in mpi_mean_jax
    res, token = mpi_sum_jax(x, token=token, comm=comm)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/utils/mpi/primitives.py", line 58, in mpi_sum_jax
    return mpi4jax.allreduce(x, op=MPI.SUM, comm=comm, token=token)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    return function(*args, **kwargs)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/mpi4jax/_src/collective_ops/allreduce.py", line 66, in allreduce
    return tuple(mpi_allreduce_p.bind(x, token, op=op, comm=comm, transpose=False))
jax._src.source_info_util.JaxStackTraceBeforeTransformation: AttributeError: '_thread._local' object has no attribute 'platforms_to_flush'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1823, in _callback_input_received
    return callback(arrays, device)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1167, in _outside_call_run_callback
    res = callback(arg, device, unpacked_transforms)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 721, in __call__
    return self.callback_func(arg)
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/experimental/driver/tdvp.py", line 540, in <lambda>
    lambda args_and_kw: odefun(state, driver, *args_and_kw[0], **args_and_kw[1]),
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/experimental/driver/tdvp.py", line 504, in odefun
    driver._loss_stats, driver._loss_grad = state.expect_and_grad(
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/vqs/mc/mc_state/state.py", line 595, in expect_and_grad
    return expect_and_grad(
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/vqs/base.py", line 381, in expect_and_grad
    return expect_and_grad(
  File "/home/filippovicentini/Dropbox/Ricerca/Codes/Python/netket/netket/vqs/mc/mc_state/expect_grad_chunked.py", line 49, in expect_and_grad_nochunking
    return expect_and_grad(vstate, operator, use_covariance, *args, **kwargs)
  File "/home/filippovicentini/Dropbox/Ricerca/12-redo/ARDM/ARDM/vqs/expect_mc_grad.py", line 54, in expect_and_grad
    Ō, Ō_grad, new_model_state = grad_expect_hermitian(
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/_src/api.py", line 466, in cache_miss
    out_flat = xla.xla_call(
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/core.py", line 1771, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/core.py", line 1787, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/core.py", line 660, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/_src/dispatch.py", line 149, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/_src/dispatch.py", line 197, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/_src/dispatch.py", line 296, in lower_xla_callable
    module = mlir.lower_jaxpr_to_module(
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/mlir.py", line 524, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/mlir.py", line 688, in lower_jaxpr_to_fun
    out_vals = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/mlir.py", line 789, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/mlir.py", line 991, in cached_lowering
    func = _emit_lowering_rule_as_fun(partial(f, **params), ctx)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/mlir.py", line 724, in _emit_lowering_rule_as_fun
    outs = lowering_rule(ctx, *_unwrap_singleton_ir_values(unflattened_args))
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/mlir.py", line 1007, in fallback
    xla_computation = xla.primitive_subcomputation(
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/xla.py", line 444, in primitive_subcomputation
    ans = f(ctx.replace(builder=c), avals, None, *xla_args, **params)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/xla.py", line 982, in f_new
    return jaxpr_subcomp(ctx, jaxpr, _xla_consts(ctx.builder, consts),
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/xla.py", line 609, in jaxpr_subcomp
    ans = rule(eqn_ctx, map(aval, eqn.invars), map(aval, eqn.outvars),
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/jax/interpreters/xla.py", line 904, in wrapped
    ans = f(ctx.builder, *args, **kw)
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/mpi4jax/_src/decorators.py", line 115, in wrapped
    f()
  File "/home/filippovicentini/Documents/pythonenvs/12-ardm/python-3.9.7/lib/python3.9/site-packages/mpi4jax/_src/decorators.py", line 16, in ensure_platform_flush
    if platform in _runtime_state.platforms_to_flush:
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: '_thread._local' object has no attribute 'platforms_to_flush'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

```

**Comment by PhilipVinc** [comment]
Indeed. Adding a 
```
    if not hasattr(_runtime_state, "platforms_to_flush"):
        return
```
check to `def ensure_platform_flush(platform)` and a similar one to `setup_cuda_mpi` solves the issue.

I think that what is happening is that `_runtime_state = threading.local()` in a callback from the GPU is not the same thread that exists on the original python thread.

It's a bit weird because if runtime state is defined, how come it does not come with `platforms_to_flush` and `cuda_mpi_setup_done` ?

I'm unsure if this approach is correct
