### ISSUE TITLE
ImportError: The mpi4jax GPU extensions could not be imported. Please re-build mpi4jax with CUDA support and try again.

### ISSUE THREAD

**Issue by HuangLianghong** [mpi4jax/mpi4jax#181]
Hi, I install mpi4jax via conda, and I can run the example app in CPU, but was failed when using GPU. My installation instruction are:
```
conda create -n mpi4jax
conda activate mpi4jax
conda install jax=0.3.24 cuda-nvcc -c conda-forge -c nvidia
export CUDA_ROOT=/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/cuda-11.7.0-ashdheyhbseykc4xaxtdx7tgbjvncj3s   #CUDA is installed via spack
conda install -c conda-forge mpi4jax
```
When I use `JAX_PLATFORM_NAME=cpu mpirun -n 1 -- python examples/shallow_water.py --benchmark`, it work, but with `JAX_PLATFORM_NAME=gpu mpirun -n 1 -- python examples/shallow_water.py --benchmark`, error occured:
```
Traceback (most recent call last):
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1120, in _lower_jaxpr_to_fun_cached
    func_op = ctx.cached_call_jaxpr_lowerings[key]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: ('enforce_boundaries', { lambda ; a:f32[182,362] b:Tok. let
    c:f32[182] = broadcast_in_dim[broadcast_dimensions=() shape=(182,)] 0.0
    d:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 1
    e:f32[182] = gather[
      dimension_numbers=GatherDimensionNumbers(offset_dims=(0,), collapsed_slice_dims=(1,), start_index_map=(1,))
      fill_value=None
      indices_are_sorted=True
      mode=GatherScatterMode.PROMISE_IN_BOUNDS
      slice_sizes=(182, 1)
      unique_indices=True
    ] a d
    f:f32[182] g:Tok = sendrecv_mpi[
      _must_transpose=False
      comm=<mpi4jax._src.utils.HashableMPIType object at 0x7f33091b6050>
      dest=0
      recvtag=-1
      sendtag=0
      source=0
      status=None
    ] e c b
    h:i32[] = add -1 362
    i:i32[] = convert_element_type[new_dtype=int32 weak_type=False] h
    j:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] i
    k:f32[182,362] = scatter[
      dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(1,), scatter_dims_to_operand_dims=(1,))
      indices_are_sorted=True
      mode=GatherScatterMode.FILL_OR_DROP
      unique_indices=True
      update_consts=()
      update_jaxpr={ lambda ; l:f32[] m:f32[]. let  in (m,) }
    ] a j f
    n:f32[182] = broadcast_in_dim[broadcast_dimensions=() shape=(182,)] 0.0
    o:i32[] = add -2 362
    p:i32[] = convert_element_type[new_dtype=int32 weak_type=False] o
    q:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] p
    r:f32[182] = gather[
      dimension_numbers=GatherDimensionNumbers(offset_dims=(0,), collapsed_slice_dims=(1,), start_index_map=(1,))
      fill_value=None
      indices_are_sorted=True
      mode=GatherScatterMode.PROMISE_IN_BOUNDS
      slice_sizes=(182, 1)
      unique_indices=True
    ] k q
    s:f32[182] t:Tok = sendrecv_mpi[
      _must_transpose=False
      comm=<mpi4jax._src.utils.HashableMPIType object at 0x7f33091c10d0>
      dest=0
      recvtag=-1
      sendtag=0
      source=0
      status=None
    ] r n g
    u:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    v:f32[182,362] = scatter[
      dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(1,), scatter_dims_to_operand_dims=(1,))
      indices_are_sorted=True
      mode=GatherScatterMode.FILL_OR_DROP
      unique_indices=True
      update_consts=()
      update_jaxpr={ lambda ; l:f32[] m:f32[]. let  in (m,) }
    ] k u s
  in (v, t) }, ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)

  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()

  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 166, in get_initial_conditions
    h0_local, token = enforce_boundaries(h0_local, "h", token)

  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 255, in enforce_boundaries
    recv_arr, token = mpi4jax.sendrecv(

  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    return function(*args, **kwargs)

  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/mpi4jax/_src/collective_ops/sendrecv.py", line 91, in sendrecv
    mpi_sendrecv_p.bind(

jax._src.source_info_util.JaxStackTraceBeforeTransformation: ImportError: The mpi4jax GPU extensions could not be imported. Please re-build mpi4jax with CUDA support and try again.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/_src/api.py", line 620, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/_src/dispatch.py", line 236, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/linear_util.py", line 300, in memoized_fun
    ans = call(fun, *args)
          ^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/_src/dispatch.py", line 359, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/_src/dispatch.py", line 515, in lower_xla_callable
    lowering_result = mlir.lower_jaxpr_to_module(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 645, in lower_jaxpr_to_module
    lower_jaxpr_to_fun(
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 915, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1043, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1152, in _xla_call_lower
    out_nodes, tokens = _call_lowering(
                        ^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1138, in _call_lowering
    symbol_name = _lower_jaxpr_to_fun_cached(ctx, fn_name, call_jaxpr, effects).name.value
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1122, in _lower_jaxpr_to_fun_cached
    func_op = lower_jaxpr_to_fun(ctx, fn_name, call_jaxpr, effects)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 915, in lower_jaxpr_to_fun
    out_vals, tokens_out = jaxpr_subcomp(ctx.replace(name_stack=callee_name_stack),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1043, in jaxpr_subcomp
    ans = rule(rule_ctx, *map(_unwrap_singleton_ir_values, in_nodes),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1309, in cached_lowering
    func = _emit_lowering_rule_as_fun(partial(f, **params), ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 964, in _emit_lowering_rule_as_fun
    outs = lowering_rule(sub_ctx, *_unwrap_singleton_ir_values(unflattened_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/mlir.py", line 1370, in fallback
    xla_computation = xla.primitive_subcomputation(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/xla.py", line 314, in primitive_subcomputation
    ans = rule(ctx, avals_in, avals_out, *xla_args, **params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/jax/interpreters/xla.py", line 546, in wrapped
    ans = f(ctx.builder, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/mpi4jax/_src/decorators.py", line 106, in wrapped
    f()
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/mpi4jax/_src/decorators.py", line 31, in ensure_gpu_ext
    raise ImportError(
jax._src.traceback_util.UnfilteredStackTrace: ImportError: The mpi4jax GPU extensions could not be imported. Please re-build mpi4jax with CUDA support and try again.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/mpi4jax/examples/shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/mpi4jax/_src/decorators.py", line 106, in wrapped
    f()
  File "/mnt/sda/2022-0526/home/hlh/spack/opt/spack/linux-debian11-zen2/gcc-10.2.1/anaconda3-2021.05-7uytzr42k74zc3ixfa3c7sywgyzxdr24/envs/mpijax/lib/python3.11/site-packages/mpi4jax/_src/decorators.py", line 31, in ensure_gpu_ext
    raise ImportError(
ImportError: The mpi4jax GPU extensions could not be imported. Please re-build mpi4jax with CUDA support and try again.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56106,1],0]
  Exit code:    1

```
How can I fix this error?

**Comment by HuangLianghong** [comment]
Thanks for your reply! I finally install mpi4jax via pip, and now I can run the demo with CPU and GPU.

But when use `MPI4JAX_USE_CUDA_MPI=1`, I get a segmentation fault like #106. Without this setting is ok for most situations, right? Installation with pip is not easy, it may failed with the wrong sofeware version. I hope I don't need to figure it out the 
complete installation :(
