### ISSUE TITLE
unexpected keyword argument 'out_types'

### ISSUE THREAD

**Issue by smartalecH** [mpi4jax/mpi4jax#215]
I'm running the simple example from the README, but get the following error:

```
Traceback (most recent call last):
  File "/private/home/alechammond/uLED_TO-main/mwe.py", line 16, in <module>
    result = foo(a)
  File "/private/home/alechammond/micromamba/envs/fmmax/lib/python3.10/site-packages/mpi4jax/_src/decorators.py", line 90, in wrapped
    return func(*args, **kwargs)
  File "/private/home/alechammond/micromamba/envs/fmmax/lib/python3.10/site-packages/mpi4jax/_src/collective_ops/allreduce.py", line 157, in mpi_allreduce_xla_encode_gpu
    return hlo_custom_call(
TypeError: custom_call() got an unexpected keyword argument 'out_types'
```

Here's my environment:

```
$ pip list | grep jax
jax                      0.4.16
jaxlib                   0.4.16+cuda11.cudnn86
mpi4jax                  0.3.14.post9

$ mpirun --version           
mpirun (Open MPI) 4.1.5
```

Any ideas on how I can debug things? Thanks!

**Comment by smartalecH** [comment]
Oof looks like an API break on the jax/jaxlib side?

https://github.com/google/jax/commit/24f9011d49f974fa24613206c5af774089ecf346

Specifically, `out_types` is now `result_types `. There may be a few other important changes there.

**Comment by dionhaefner** [comment]
Thanks. Looks like we missed to update some GPU translation rules (which are not tested on CI).
