### ISSUE TITLE
Mpi4jax + jax[cuda12]

### ISSUE THREAD

**Issue by PhilipVinc** [mpi4jax/mpi4jax#235]
I recently found out that a relatively easy (and pain free) way to install mpi4jax is to use a local `CUDA version>12.0` to compile mpi4jax, but run jax using the wheels using the PyPi cuda version.

This works because of the forward compatibility ABI guarantees of CUDA. The procedure is something like

```bash
cat Install
ENV_NAME=myenv2
module load mambaforge gcc/10.2.0 openmpi/4.1.4 cuda/12.2
mamba create --name $ENV_NAME python=3.11 
conda activate $ENV_NAME

# install pip
pip install --upgrade pip
# Remove cache to be sure because pip keeps around some copies of mpi4jax
pip cache purge
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install --upgrade mpi4jax
``` 

run 
```python
module purge
module load mambaforge gcc/10.2.0 openmpi/4.1.4
conda activate $ENV_NAME

mpirun -n $SLURM_NTASKS python yourscript.py
```

As jax has stated that they will sunset `cuda12_pip` in favour of `cuda12` and the new pjrt mechanism, I started looking into it and found some issues.

First, If I install mpi4jax + `jax[cuda12]`, I get the following error:
```python
python -c "import jax; jax.devices(); import mpi4jax"
Jax plugin configuration error: Exception when calling jax_plugins.xla_cuda12.initialize()
Traceback (most recent call last):
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jax/_src/xla_bridge.py", line 614, in discover_pjrt_plugins
    plugin_module.initialize()
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jax_plugins/xla_cuda12/__init__.py", line 83, in initialize
    xla_client.register_custom_call_handler(
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jaxlib/xla_client.py", line 633, in register_custom_call_handler
    handler(name, fn, xla_platform_name, api_version)
TypeError: register_custom_call_target(): incompatible function arguments. The following argument types are supported:
    1. register_custom_call_target(c_api: capsule, fn_name: str, fn: capsule, xla_platform_name: str, api_version: int = 0) -> None

Invoked with types: PyCapsule, bytes, PyCapsule, str, int
```

which is triggered when registering custom_calls for the `CUDA` backend. It seems that suddenly it does not like anymore our names of targets which are stored in bytes. 

So I changed the registration in `xla_bridge/__init__.py` to

```python
if HAS_GPU_EXT:
    for name, fn in mpi_xla_bridge_gpu.gpu_custom_call_targets.items():
        xla_client.register_custom_call_target(str(name), fn, platform="CUDA", api_version=0)
```

which has the right type, which now initialises successfully but running some code depending on mpi4jax will raise the following warning
```python
  File "/mnt/beegfs/home/CPHT/filippo.vicentini/test2/netket/netket/jax/_utils_random.py", line 40, in <lambda>
    lambda k: mpi.mpi_bcast_jax(k, root=root, comm=comm)[0], key
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/home/CPHT/filippo.vicentini/test2/netket/netket/utils/mpi/primitives.py", line 271, in mpi_bcast_jax
    return mpi4jax.bcast(x, token=token, root=root, comm=comm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/home/CPHT/filippo.vicentini/test2/mpi4jax/mpi4jax/_src/validation.py", line 90, in wrapped
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/home/CPHT/filippo.vicentini/test2/mpi4jax/mpi4jax/_src/collective_ops/bcast.py", line 81, in bcast
    res, token = mpi_bcast_p.bind(x, token, root=root, comm=comm)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/beegfs/workdir/filippo.vicentini/mambaforge/envs/ENV_NAME/lib/python3.11/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
           ^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: No registered implementation for custom call to mpi_bcast for platform CUDA
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

Which suggests that the custom calls where not successfully registered?

Interestingly, I cannot inspect what customs calls are registered on gpu. On CPU I can do 
```python
from jax.lib import xla_client
print(list(xla_client.custom_call_targets("Host").keys()))
```
which presents a long list of custom calls, including the mpi ones, but if I use `"CUDA"` or `"gpu"` instead of Host, the list is empty....

@dionhaefner do you have any vague idea of what might be going on?

**Comment by dionhaefner** [comment]
I'm not sure if trying to make this work is worth it. Why not try to use the bundled CUDA for building `mpi4jax`? I.e., setting `CUDA_ROOT` / other search paths in `setup.py` to wherever `jax[cuda12]` installs the runtime.

**Comment by PhilipVinc** [comment]
Because the visa version on pypi lacks nvcc.
Though you are rights maybe the headers and libraries are enough..?

**Comment by dionhaefner** [comment]
Yea I don't think we're using NVCC, no cuda kernels are being built after all.

**Comment by PhilipVinc** [comment]
Just tried it and it works and solves a lot of problems!

I modified setup.py `get_cuda_path` as follows:

```python
def get_cuda_path():
    # try to check if nvidia-cuda-nvcc-cu* is installed
    # we need to get the site-packages of this install. to do so we use
    # mpi4py which must be installed
    mpi4py_spec = importlib.util.find_spec("mpi4py")
    depot_path = pathlib.Path(os.path.dirname(mpi4py_spec.origin)).parent
    # below is taken from  
    # https://github.com/google/jax/blob/4cca2335220dcc953edd2ac764b2387e53527495/jax/_src/lib/__init__.py#L129
    #
    # If the pip package nvidia-cuda-nvcc-cu11 is installed, it should have
    # both of the things XLA looks for in the cuda path, namely bin/ptxas and
    # nvvm/libdevice/libdevice.10.bc
    maybe_cuda_path = depot_path / "nvidia" / "cuda_nvcc"
    if maybe_cuda_path.is_dir():
        print("Using CUDA_PATH from nvidia-cuda-nvcc-cu* package: ", maybe_cuda_path)
        return str(maybe_cuda_path)
    
    # old logic below
    nvcc_path = search_on_path(("nvcc", "nvcc.exe"))
    ...
```

Which makes sense, as jax prioritises it's internal distribution anyway.

The main issue I find is that jax is checking the path of `jaxlib`at runtime to resolve the cuda path 
(see https://github.com/google/jax/blob/4cca2335220dcc953edd2ac764b2387e53527495/jax/_src/lib/__init__.py#L128 ). 

I'm not sure how we can query a package install directory at setup time. I tried the code above which checks the path of mpi4py, which is a build-time dependency.
But pip compiles packages in a virtual environment isolated from everything else.

To get the code above to work I had to run it with
```
pip install -e . --no-build-isolation
```

The best alternative would be for us to be able to query the target folder and check if nvidia/ exists in there...

**Comment by dionhaefner** [comment]
CC #220
