### ISSUE TITLE
shallow_water example: TypeError: 'TokenType' object is not iterable

### ISSUE THREAD

**Issue by benkirk** [mpi4jax/mpi4jax#260]
(Same as #256)

What is the most recent version of Jax tested - should I roll back from `0.4.31`?

I'm attempting to run the shallow water benchmark with the following host environment:
```pre
jax                0.4.31
jax-cuda12-pjrt    0.4.31
jax-cuda12-plugin  0.4.31
jaxlib             0.4.31
mpi4jax            0.5.3
mpi4py             4.0.0
```
and receive this error message:

```pre
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 584, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 428, in solve_shallow_water
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 168, in get_initial_conditions
    h0_local, token = enforce_boundaries(h0_local, "h", token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 255, in enforce_boundaries
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 584, in <module>
    token = mpi4jax.send(send_arr, dest=send_proc, comm=mpi_comm, token=token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.11/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    return function(*args, **kwargs)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.11/site-packages/mpi4jax/_src/collective_ops/send.py", line 75, in send
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 428, in solve_shallow_water
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 168, in get_initial_conditions
    return mpi_send_p.bind(x, token, dest=dest, tag=tag, comm=comm)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'TokenType' object is not iterable
```

and the summary
```pre
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
    for op in operands:
              ^^^^^^^^
TypeError: 'TokenType' object is not iterable
```

**Comment by dionhaefner** [comment]
Not sure how to debug this without a reproducer. I notice that the line numbers are not the same as [here](https://github.com/mpi4jax/mpi4jax/blob/master/examples/shallow_water.py), so please let us know which changes you made and how you are invoking the script.

**Comment by benkirk** [comment]
What version of Jax are you running?  These line numbers should match exactly:

```bash
wget https://raw.githubusercontent.com/mpi4jax/mpi4jax/master/examples/shallow_water.py
mpiexec -n 4 -ppn 4 python ./shallow_water.py 
```
Then,

```pre
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 166, in get_initial_conditions
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 166, in get_initial_conditions
    h0_local, token = enforce_boundaries(h0_local, "h", token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 253, in enforce_boundaries
    token = mpi4jax.send(send_arr, dest=send_proc, comm=mpi_comm, token=token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    h0_local, token = enforce_boundaries(h0_local, "h", token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 253, in enforce_boundaries
    token = mpi4jax.send(send_arr, dest=send_proc, comm=mpi_comm, token=token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 166, in get_initial_conditions
    h0_local, token = enforce_boundaries(h0_local, "h", token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 253, in enforce_boundaries
    token = mpi4jax.send(send_arr, dest=send_proc, comm=mpi_comm, token=token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 166, in get_initial_conditions
    h0_local, token = enforce_boundaries(h0_local, "h", token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 253, in enforce_boundaries
    token = mpi4jax.send(send_arr, dest=send_proc, comm=mpi_comm, token=token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    return function(*args, **kwargs)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 75, in send
    return function(*args, **kwargs)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 75, in send
    return function(*args, **kwargs)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 75, in send
    return function(*args, **kwargs)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 75, in send
    return mpi_send_p.bind(x, token, dest=dest, tag=tag, comm=comm)
    return mpi_send_p.bind(x, token, dest=dest, tag=tag, comm=comm)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'TokenType' object is not iterable

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'TokenType' object is not iterable

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
    return mpi_send_p.bind(x, token, dest=dest, tag=tag, comm=comm)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'TokenType' object is not iterable

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/decorators.py", line 130, in wrapped
    return mpi_send_p.bind(x, token, dest=dest, tag=tag, comm=comm)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'TokenType' object is not iterable

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/tests/./shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/decorators.py", line 130, in wrapped
    h, u, v = get_initial_conditions()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/decorators.py", line 130, in wrapped
    h, u, v = get_initial_conditions()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/decorators.py", line 130, in wrapped
    return func(*args, **kwargs)
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 148, in mpi_send_xla_encode_device
           ^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 148, in mpi_send_xla_encode_device
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 148, in mpi_send_xla_encode_device
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 148, in mpi_send_xla_encode_device
    result_layouts=get_default_layouts(out_types),
    result_layouts=get_default_layouts(out_types),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/utils.py", line 60, in get_default_layouts
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/utils.py", line 60, in get_default_layouts
    result_layouts=get_default_layouts(out_types),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/utils.py", line 60, in get_default_layouts
    result_layouts=get_default_layouts(out_types),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/utils.py", line 60, in get_default_layouts
    for op in operands:
    for op in operands:
              ^^^^^^^^
TypeError: 'TokenType' object is not iterable
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
    for op in operands:
              ^^^^^^^^
TypeError: 'TokenType' object is not iterable
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
              ^^^^^^^^
TypeError: 'TokenType' object is not iterable
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
    for op in operands:
              ^^^^^^^^
TypeError: 'TokenType' object is not iterable
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
deg0040.hsn.de.hpc.ucar.edu: rank 1 exited with code 1```

**Comment by benkirk** [comment]
This is triggered from `utils.py` `for op in operands:` [here](https://github.com/mpi4jax/mpi4jax/blob/390ca9581b245e9f6c62eb6b34289050c2f4d4ac/mpi4jax/_src/utils.py#L60).

Tracing that call back, the arguments that are failing are:
```pre
type(operands) = <class 'importlib._bootstrap.TokenType'>
operands = !stablehlo.token
```

Which is triggered from
```pre
Traceback (most recent call last):
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 582, in <module>
    sol = solve_shallow_water(t1=10 * DAY_IN_SECONDS, num_multisteps=PLOT_EVERY)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 426, in solve_shallow_water
    h, u, v = get_initial_conditions()
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 166, in get_initial_conditions
    h0_local, token = enforce_boundaries(h0_local, "h", token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/./tests/mpi4jax_shallow_water.py", line 253, in enforce_boundaries
    token = mpi4jax.send(send_arr, dest=send_proc, comm=mpi_comm, token=token)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/validation.py", line 90, in wrapped
    return function(*args, **kwargs)
  File "/glade/derecho/scratch/benkirk/conda-recipes/test_envs/mpi4jax/lib/python3.12/site-packages/mpi4jax/_src/collective_ops/send.py", line 76, in send
    return mpi_send_p.bind(x, token, dest=dest, tag=tag, comm=comm)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: 'TokenType' object is not iterable
```

I'm no Jax expert, so not sure what to do with that - thanks!!

**Comment by dionhaefner** [comment]
Thanks, that helped – I didn't realize this was on GPU. I pushed a fix [here](https://github.com/mpi4jax/mpi4jax/pull/261), would you be able to test that?

**Comment by benkirk** [comment]
I was able to port those simple changes into my installation and that runs, thanks!

That has me running on our 4-way A100 nodes on a Cray-EX with Slingshot 11 as the network.  Weirdly it runs slower on the GPUs than CPU vs. your published example results, but I'll investigate that separately.

**Comment by PhilipVinc** [comment]
Are you using `export MPI4JAX_USE_CUDA_MPI=1`?

**Comment by benkirk** [comment]
ooh, I'm using the default small domain so that observation is a red herring...

**Comment by benkirk** [comment]
With the `[3600,1800]` domain then on 8 ranks, (2 nodes, 4 ea.)











- `JAX_PLATFORM_NAME=cpu mpiexec -n 8 -ppn 4 python ./tests/mpi4jax_shallow_water.py --benchmark`:  
   **161.77s/model day**

- `JAX_PLATFORM_NAME=gpu MPI4JAX_USE_CUDA_MPI=0 mpiexec -n 8 -ppn 4 python ./tests/mpi4jax_shallow_water.py --benchmark`: 
   **12.24s/model day**

- `JAX_PLATFORM_NAME=gpu MPI4JAX_USE_CUDA_MPI=1 mpiexec -n 8 -ppn 4 python ./tests/mpi4jax_shallow_water.py --benchmark`: 
   **6.79s**
   
   ---
   
   Thanks for the help @PhilipVinc & @dionhaefner !

**Comment by PhilipVinc** [comment]
Is this reasonable performance?

**Comment by benkirk** [comment]
Having never run this before, a little hard to say but purely comparing to https://mpi4jax.readthedocs.io/en/latest/shallow-water.html#benchmarks I think so.

Our A100s should be quite a bit faster than the P100s from the benchmark; I'll need to run on just 2 for a 1:1 comparison.  I see quite an impact from `MPI4JAX_USE_CUDA_MPI=1` even on 2 nodes, I'd expect that to hold as I scale up.
