### ISSUE TITLE
Error in differentiating a function with multiple components

### ISSUE THREAD

**Issue by shinaoka** [mpi4jax/mpi4jax#72]
I encountered a runtime error when I ran the following code with one MPI process.
The bottom line is that jax fails to differentiate a function which adds two values allreduced by mpi4jax.
Is this intended behavior?

* mpi4jax-0.2.16 and 0.2.16+5.ga28c335
* jax   0.2.11
* jaxlib   0.1.64
* mpi4py 3.0.3
* Python 3.8.5

## Code

```
from mpi4py import MPI
import jax
import jax.numpy as jnp
import mpi4jax

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

def foo(x):
    token = None
    x1, token = mpi4jax.allreduce(x**2, op=MPI.SUM, comm=comm, token=token)
    x2, token = mpi4jax.allreduce(jnp.abs(x), op=MPI.SUM, comm=comm, token=token)
    return x1 + x2

x = 0.0
fx = foo(x)
gfoo = jax.grad(foo)
gx = gfoo(x)
```

## Error messages
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "mpi.py", line 18, in <module>
    gx = gfoo(x)
jax._src.traceback_util.FilteredStackTrace: KeyError: <class 'jax.interpreters.xla.Token'>

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mpi.py", line 18, in <module>
    gx = gfoo(x)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/api.py", line 752, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/api.py", line 821, in value_and_grad_f
    g = vjp_py(np.ones((), dtype=dtype))
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/api.py", line 1808, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 121, in unbound_vjp
    arg_cts = backward_pass(jaxpr, consts, dummy_args, cts)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 231, in backward_pass
    map(partial(write_cotangent, eqn.primitive), eqn.invars, cts_out)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/_src/util.py", line 40, in safe_map
    return list(map(f, *args))
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 176, in write_cotangent
    ct_env[v] = add_tangents(ct_env[v], ct) if v in ct_env else ct
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 482, in add_tangents
    return add_jaxvals(x, y)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/ad_util.py", line 37, in add_jaxvals
    return add_jaxvals_p.bind(x, y)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/core.py", line 259, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/core.py", line 597, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/ad_util.py", line 44, in add_impl
    return jaxval_adders[type(xs)](xs, ys)
KeyError: <class 'jax.interpreters.xla.Token'>
Traceback (most recent call last):
  File "mpi.py", line 18, in <module>
    gx = gfoo(x)
jax._src.traceback_util.FilteredStackTrace: KeyError: <class 'jax.interpreters.xla.Token'>

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mpi.py", line 18, in <module>
    gx = gfoo(x)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/api.py", line 752, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/api.py", line 821, in value_and_grad_f
    g = vjp_py(np.ones((), dtype=dtype))
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/api.py", line 1808, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 121, in unbound_vjp
    arg_cts = backward_pass(jaxpr, consts, dummy_args, cts)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 231, in backward_pass
    map(partial(write_cotangent, eqn.primitive), eqn.invars, cts_out)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/_src/util.py", line 40, in safe_map
    return list(map(f, *args))
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 176, in write_cotangent
    ct_env[v] = add_tangents(ct_env[v], ct) if v in ct_env else ct
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/interpreters/ad.py", line 482, in add_tangents
    return add_jaxvals(x, y)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/ad_util.py", line 37, in add_jaxvals
    return add_jaxvals_p.bind(x, y)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/core.py", line 259, in bind
    out = top_trace.process_primitive(self, tracers, params)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/core.py", line 597, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/shinaoka/.local/lib/python3.8/site-packages/jax/ad_util.py", line 44, in add_impl
    return jaxval_adders[type(xs)](xs, ys)
KeyError: <class 'jax.interpreters.xla.Token'>
```

**Comment by dionhaefner** [comment]
Thanks for the report. I can reproduce this and will work on a fix.

**Comment by PhilipVinc** [comment]
I`m unsure about what is causing this, but I think that If we rewrite the transposition logic and jvp to use https://github.com/google/jax/pull/5781 we _might_ avoid errors.

**Comment by PhilipVinc** [comment]
I think it's a Jax error because he is trying to add two tokens, which of course is an operation that does not exist...

**Comment by shinaoka** [comment]
Hi, thank you for your efforts.
I am quite new to JAX and no opinion on the source of the error.
Do you think that we should transfer this report to the JAX issue page?

**Comment by dionhaefner** [comment]
I don't think our JVP rule is 100% correct. The internal calls to `allreduce` need to use the same token and pass it along. Something like this:

```python
def mpi_allreduce_value_and_jvp(in_args, tan_args, op, comm, transpose):
    x, token = in_args
    x_tan, _ = tan_args

    if unpack_hashable(op) != _MPI.SUM:
        raise NotImplementedError(
            "The adjoint of allreduce is only defined for op=MPI.SUM"
        )

    val, token = mpi_allreduce_p.bind(x, token, op=op, comm=comm, transpose=transpose)
    jvp, token = mpi_allreduce_p.bind(x_tan, token, op=op, comm=comm, transpose=transpose)
    return (val, token), (jvp, ad.Zero.from_value(token))
```

Unfortunately, this throws a different, even more cryptic error.

**Comment by dionhaefner** [comment]
Looks like we need to open an issue. I'm out of ideas to debug this.

**Comment by dionhaefner** [comment]
https://github.com/google/jax/issues/6285

**Comment by inailuig** [comment]
> I`m unsure about what is causing this, but I think that If we rewrite the transposition logic and jvp to use [google/jax#5781](https://github.com/google/jax/pull/5781) we _might_ avoid errors.

I had tried this some time ago, but ran into 2 issues: 
- couldn't figure out how to return the token as a side-effect (passing it as residual_args and eating it works) 
- linear_call does not work yet with jit

**Comment by dionhaefner** [comment]
Hope that fixes it for now, let us know if you run into further problems.
